name: Get a list of files on PR
on: [pull_request]
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: Get files from pull request
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json
          echo 'FILES : ${{ steps.file_changes.outputs.files}}\n'
          echo 'MODIFIED : ${{ steps.file_changes.outputs.files_modified}}\n'
          echo 'ADDED : ${{ steps.file_changes.outputs.files_added}}\n'
          echo 'REMOVED : ${{ steps.file_changes.outputs.files_removed}}\n'
