name: Get a list of files on PR

on: [push, pull_request]
    
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json
          echo ''
          echo 'FILES : ${{ steps.file_changes.outputs.files}}'
          echo 'MODIFIED : ${{ steps.file_changes.outputs.files_modified}}'
          echo 'ADDED : ${{ steps.file_changes.outputs.files_added}}'
          echo 'REMOVED : ${{ steps.file_changes.outputs.files_removed}}'
