name: V setup
on:
  push:
    branches: [v-test]
  pull_request:
    branches: [v-test]
    types: [opened, synchronize]
    
jobs:
 test:
  name: Run tests on ${{ matrix.os }} ${{ matrix.v-version }}
  strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        v-version: [master, latest]
  runs-on: ${{ matrix.os }}
  steps:
      - uses: actions/checkout@v2
      - uses: nocturlab/setup-vlang-action@master
        with:
          v-version: master
      - name: Run fixed-test
        run: v fixed-test
      - name: v fmt verify
        run: v fmt -verify -diff *.v
